on:
  workflow_call:
    inputs:
      image_name:
        required: true
        type: string

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Echo
        run: |
          echo "${{ inputs.image_name }}"