name: Test CI

on:
  push:
    branches:
      - main
  pull_request_target:
    types:
      - opened
      - reopened
      - synchronize
    branches:
      - main

jobs:
  authorize:
    runs-on: ubuntu-latest
    environment:
      ${{ github.event.name == 'pull_request_target' &&
      github.event.pull_request.head.repo.full_name != github.repository &&
      'external' || 'internal' }}
    steps:
      - run: echo "${{ github.event.name }}"
      - run: echo "${{ github.event.pull_request.head.repo.full_name }}"
      - run: echo "${{ github.repository }}"
      - run: echo "$GITHUB_CONTEXT"
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}

  test-job:
    needs: authorize
    name: Checkout Test
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout code"
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PULL_TOKEN }}
          fetch-depth: 0
          submodules: recursive
      - name: 'Run LS'
        run: |
          ls
      - name: 'Run submodule LS'
        run: |
          ls submodule